project:
  type: website
  output-dir: "../docs/sw"

website:
  back-to-top-navigation: true
  navbar:
    pinned: false
    left:
      - text: "Nyumbani"
        href: index.qmd
      - text: "Kuhusu"
        menu:
          - text: "Usuli"
            href: Background.qmd
          - text: "Muundo wa Utafiti"
            href: Design.qmd
          - text: "Uingiliaji Kati"
            href: Intervention.qmd
      - text: "Hati"
        menu:
          - text: "Itifaki"
            href: Protocol.qmd
          - text: "Machapisho"
            href: Publications.qmd
      - text: "Timu"
        href: Principal.qmd
      - text: "Washirika"
        href: Funding.qmd
      - text: "Habari"
        href: news.qmd
    right:
      - text: "🌍 Lugha"
        menu:
          - text: "English"
            href: ../en/index.html
      - icon: github
        text: Chanzo
        href: https://github.com/alainamstutz/DAWA_website
      - icon: envelope
        text: Barua pepe
        href: mailto:rainer.tan@unisante.ch
  page-footer: © 2026 Mradi wa DAWA &middot; Imetengenezwa na [![](https://quarto.org/quarto.png){fig-alt="Quarto" width=65px}](https://quarto.org/) &middot; Kiolezo cha tovuti na [Christof Schönenberger](https://github.com/christofmanuel)
  search:
    location: navbar
    type: textbox

html:
  theme: [quartz, ../styles.css]
  backgroundcolor: "#F0F7F4"
  mainfont: "Arial, sans-serif"
  fontsize: 1.6rem
  fontcolor: "#1B3A2D"
  footer: "#1A3D2B"

editor: visual
