project:
  type: website
  output-dir: "../docs/en"

website:
  back-to-top-navigation: true
  navbar:
    pinned: false
    left:
      - text: "Home"
        href: index.qmd
      - text: "About"
        menu:
          - text: "Background"
            href: Background.qmd
          - text: "Study Design"
            href: Design.qmd
          - text: "Intervention"
            href: Intervention.qmd
      - text: "Documents"
        menu:
          - text: "Protocol"
            href: Protocol.qmd
          - text: "Publications"
            href: Publications.qmd
      - text: "Team"
        href: Principal.qmd
      - text: "Partners"
        href: Funding.qmd
      - text: "News"
        href: news.qmd
    right:
      - text: "🌍 Language"
        menu:
          - text: "Kiswahili"
            href: ../sw/index.html
      - icon: github
        text: Source
        href: https://github.com/alainamstutz/DAWA_website
      - icon: envelope
        text: Email
        href: mailto:alain.amstutz@unisante.ch
  page-footer: © 2026 DAWA Project &middot; Made with [![](https://quarto.org/quarto.png){fig-alt="Quarto" width=65px}](https://quarto.org/) &middot; Website template by [Christof Schönenberger](https://github.com/christofmanuel)
  search:
    location: navbar
    type: textbox

html:
  theme: quartz
  backgroundcolor: "#F0F7F4"
  mainfont: "Arial, sans-serif"
  fontsize: 1.6rem
  fontcolor: "#1B3A2D"
  footer: "#1A3D2B"

style: css

editor: visual
